from MyRedBlackTree import MyRedBlackTree

my_red_black_tree = MyRedBlackTree()

my_red_black_tree.insert(10)
print(my_red_black_tree.up_down_print())
my_red_black_tree.insert(5)
print(my_red_black_tree.up_down_print())
my_red_black_tree.insert(20)
print(my_red_black_tree.up_down_print())
my_red_black_tree.insert(30)
print(my_red_black_tree.up_down_print())
my_red_black_tree.insert(40)
print(my_red_black_tree.up_down_print())
my_red_black_tree.insert(35)
print(my_red_black_tree.up_down_print())
my_red_black_tree.insert(37)
print(my_red_black_tree.up_down_print())
my_red_black_tree.insert(7)
print(my_red_black_tree.up_down_print())
my_red_black_tree.insert(6)
print(my_red_black_tree.up_down_print())
my_red_black_tree.insert(39)
print(my_red_black_tree.up_down_print())